- name: Render secrets for docker build (secrets stage)
  hosts: local
  gather_facts: false
  vars:
    out_dir: "/work/out"
  tasks:
    - name: Ensure out_dir exists
      ansible.builtin.file:
        path: "{{ out_dir }}/secrets"
        state: directory
        mode: "0700"

    - name: Render .env from vault
      ansible.builtin.template:
        src: templates/env.j2
        dest: "{{ out_dir }}/.env"
        mode: "0600"

    - name: Render gsa-dvc.json from vault
      ansible.builtin.template:
        src: templates/gsa-dvc.json.j2
        dest: "{{ out_dir }}/secrets/gsa-dvc.json"
        mode: "0600"

    - name: Append build marker
      ansible.builtin.lineinfile:
        path: "{{ out_dir }}/.env"
        line: "BUILT_AT={{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%SZ') }}"
        create: yes
        mode: "0600"

