name: CD (Build & Push to Docker Hub)

on:
  push:
    branches: [ "main" ]

concurrency:
  group: cd-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mitlyy/dbtechlab3
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=sha

      - name: Check vault secret presence (repo secret)
        run: |
          if [ -z "${ANSIBLE_VAULT_PASS}" ]; then
            echo "ANSIBLE_VAULT_PASS is EMPTY (repo secret not set)"; exit 1;
          fi
          echo "ANSIBLE_VAULT_PASS is present (value is masked)"
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Build & Push (with secrets)
        uses: docker/build-push-action@v6
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          cache-from: type=registry,ref=mitlyy/dbtechlab3:latest
          cache-to: type=inline
          secrets: |
            id=vault_pass,env=ANSIBLE_VAULT_PASS

