name: CI (Docker build + healthcheck)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check vault secret presence (repo secret)
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
        run: |
          if [ -z "${ANSIBLE_VAULT_PASS}" ]; then
            echo "ANSIBLE_VAULT_PASS is EMPTY (repo secret not available for this event)"; exit 1;
          fi
          echo "ANSIBLE_VAULT_PASS is present (value is masked)"
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Build (full, with secrets)
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false)
        uses: docker/build-push-action@v6
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mitlyy/dbtechlab3:ci-test
          provenance: false
          cache-from: type=registry,ref=mitlyy/dbtechlab3:latest
          cache-to: type=inline
          secrets: |
            id=vault_pass,env=ANSIBLE_VAULT_PASS

      - name: Build (light, no secrets) for PR from forks
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          target: deps
          tags: mitlyy/dbtechlab3:ci-light
          provenance: false

