name: CI (Docker build + healthcheck)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check vault secret presence
        run: |
          if [ -z "${ANSIBLE_VAULT_PASS}" ]; then
            echo "ANSIBLE_VAULT_PASS is EMPTY for this event"; exit 1;
          fi
          echo "ANSIBLE_VAULT_PASS is present (masked)"
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Write vault pass to file in workspace
        run: |
          printf '%s' "${ANSIBLE_VAULT_PASS}" > vault_pass
          chmod 600 vault_pass
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Build image with vault secret
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mitlyy/dbtechlab3:ci-test
          cache-from: type=registry,ref=mitlyy/dbtechlab3:latest
          cache-to: type=inline
          secret-files: |
            vault_pass=vault_pass

