jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check vault secret presence
        run: |
          if [ -z "${ANSIBLE_VAULT_PASS}" ]; then
            echo "ANSIBLE_VAULT_PASS is EMPTY (repo secret not available for this event)"; exit 1;
          fi
          echo "ANSIBLE_VAULT_PASS is present (masked)"
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Write vault pass to temp file
        run: |
          set -euo pipefail
          printf '%s' "${ANSIBLE_VAULT_PASS}" > "${RUNNER_TEMP}/vault_pass.txt"
          chmod 600 "${RUNNER_TEMP}/vault_pass.txt"
          ls -l "${RUNNER_TEMP}/vault_pass.txt"
        env:
          ANSIBLE_VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASS }}

      - name: Build (full, with secrets)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: mitlyy/dbtechlab3:ci-test
          provenance: false
          cache-from: type=registry,ref=mitlyy/dbtechlab3:latest
          cache-to: type=inline
          secrets: |
            id=vault_pass,src=${{ runner.temp }}/vault_pass.txt

